In [2]:
import pandas as pd

In [4]:
#Loading a dataset
defenders = pd.read_csv("/home/diego/Documents/0.IRONHACK/1.SEPTEMBER/Projects/3.Defenders/defenders-data.csv")

In [1]:
defenders.head(30)

NameError: name 'defenders' is not defined

In [5]:
defenders.columns

Index(['id', 'industry_driver', 'name', 'gender', 'person_characteristics',
       'event_date', 'event_country', 'involvement_perpetrator_type',
       'event_continent', 'act_type', 'year'],
      dtype='str')

In [6]:
#null values
defenders.isna().sum()

id                               0
industry_driver                  0
name                             0
gender                           0
person_characteristics          85
event_date                       0
event_country                    0
involvement_perpetrator_type    33
event_continent                  0
act_type                         0
year                             0
dtype: int64

In [7]:
defenders.dropna(axis=1) #Dropping columns with null values

,id,industry_driver,name,gender,event_date,event_country,event_continent,act_type,year
0,recX3dxigUJx6cawV,Land,Celestina Jara,Female,2012-12-10,Argentina,Americas,Murder,2012
1,rectNwUnWnra6CrB7,Land,Rafael Nahuel,Male,2017-11-25,Argentina,Americas,Murder,2017
2,recGzhVTQVC6Vk4TD,Agribusiness,Miguel Galván,Male,2012-10-10,Argentina,Americas,Murder,2012
3,recSKV5PGSRCCqHCC,Land,Lila Coyipé,Female,2012-12-10,Argentina,Americas,Murder,2012
4,recblmJBV1RWYu1sp,Agribusiness,Santiago Maldonado,Male,2017-08-01,Argentina,Americas,Murder,2017
...,...,...,...,...,...,...,...,...,...
2370,recoOmUWNVcE1b4MC,Other,Kulwa Igembe,Male,2025-05-07,Tanzania,Africa,Murder,2025
2371,recDWfiKmOtrL9bG8,Other,Hamprey Mhaki,Male,2025-04-26,Tanzania,Africa,Murder,2025
2372,recQyonX6hr3gLl9L,Agribusiness,I.G.,Male,2025-02-17,Nicaragua,Americas,Murder,2025
2373,recIACZZByTHryihw,Land,Hulyo Agtay,Male,2025-03-14,Philippines,Asia,Murder,2025
2374,recfM7aqgHI6sQpfi,Land,Juan Sumilhig,Male,2025-08-01,Philippines,Asia,Murder,2025

In [10]:
defenders["event_continent"].value_counts() #the Americas is the region with more killings

event_continent
Americas    1725
Asia         499
Africa       129
Europe        16
Oceania        6
Name: count, dtype: int64

In [7]:
pd.crosstab(defenders['event_continent'], defenders['industry_driver'])

industry_driver,Agribusiness,Hydropower,Land,Logging,Mining & Extractives,Other,Poaching,Unknown
event_continent,,,,,,,,
Africa,2,1,28,3,25,9,61,0
Americas,95,79,1012,140,200,120,4,75
Asia,95,21,135,31,155,32,13,17
Europe,0,3,3,5,1,0,4,0
Oceania,0,0,0,0,4,2,0,0

In [13]:
top_industries_world = defenders['industry_driver'].value_counts().head(5)

In [14]:
top_industries_world

industry_driver
Land                    1178
Mining & Extractives     385
Agribusiness             192
Logging                  179
Other                    163
Name: count, dtype: int64

In [8]:
defenders[defenders["event_continent"] == "Americas"]

,id,industry_driver,name,gender,person_characteristics,event_date,event_country,involvement_perpetrator_type,event_continent,act_type,year
0,recX3dxigUJx6cawV,Land,Celestina Jara,Female,Indigenous Peoples,2012-12-10,Argentina,Police,Americas,Murder,2012
1,rectNwUnWnra6CrB7,Land,Rafael Nahuel,Male,Indigenous Peoples,2017-11-25,Argentina,Police,Americas,Murder,2017
2,recGzhVTQVC6Vk4TD,Agribusiness,Miguel Galván,Male,Indigenous Peoples,2012-10-10,Argentina,Hitmen,Americas,Murder,2012
3,recSKV5PGSRCCqHCC,Land,Lila Coyipé,Female,Indigenous Peoples,2012-12-10,Argentina,Police,Americas,Murder,2012
4,recblmJBV1RWYu1sp,Agribusiness,Santiago Maldonado,Male,Demonstrators,2017-08-01,Argentina,Police,Americas,Murder,2017
...,...,...,...,...,...,...,...,...,...,...,...
2366,recusxLsNKPrDKmqN,Logging,Andy Raúl Coquinche Vásquez,Male,Indigenous Peoples,2025-11-12,Peru,Corporations,Americas,Murder,2025
2367,recAYou2nhGHpcQ4g,Land,Abel Monroy,Male,Small-scale farmer,2025-08-01,Honduras,Organised crime / mafias,Americas,Murder,2025
2368,rec72fDSS0mmChQ4J,Agribusiness,S.C.C.,Male,Indigenous Peoples,2025-09-10,Nicaragua,Other,Americas,Murder,2025
2369,recJZhT2jJQ6R3Fiz,Agribusiness,D.M.C,Male,Indigenous Peoples,2025-09-25,Nicaragua,Police,Americas,Murder,2025
2372,recQyonX6hr3gLl9L,Agribusiness,I.G.,Male,Indigenous Peoples,2025-02-17,Nicaragua,Other,Americas,Murder,2025

In [9]:
americas_df = defenders[defenders["event_continent"] == "Americas"] #Filter to focus in the Americas

In [10]:
americas_df ["event_country"].value_counts() #Countries with more killings

event_country
Colombia                    548
Brazil                      439
Mexico                      230
Honduras                    167
Guatemala                   114
Nicaragua                    77
Peru                         66
Venezuela                    23
Paraguay                     18
Ecuador                      12
Argentina                     8
Chile                         5
Panama                        5
Costa Rica                    4
Dominican Republic            4
Bolivia                       2
United States of America      2
Canada                        1
Name: count, dtype: int64

In [21]:
americas_df["industry_driver"].value_counts()

industry_driver
Land                    1012
Mining & Extractives     200
Logging                  140
Other                    120
Agribusiness              95
Hydropower                79
Unknown                   75
Poaching                   4
Name: count, dtype: int64

In [23]:
#2025
defenders_2025 = defenders[defenders["year"] == 2025]
pd.crosstab(defenders_2025['event_continent'], defenders_2025['industry_driver'])

industry_driver,Agribusiness,Hydropower,Land,Logging,Mining & Extractives,Other,Unknown
event_continent,,,,,,,
Africa,0,0,0,0,1,2,0
Americas,5,3,76,8,5,8,0
Asia,1,0,7,0,5,1,1
Europe,0,0,1,0,0,0,0

In [12]:
americas_df.to_csv("americas_df.csv", index=False)